// 项目级 build.gradle
buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://artifactory.appodeal.com/appodeal-public/' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.2'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://artifactory.appodeal.com/appodeal-public/' }
    }
}
