#!/bin/sh
#
# Gradle start up script for POSIX generated by Gradle Wrapper.
#
##############################################################################
#
#   Gradle Wrapper - DO NOT MODIFY
#
##############################################################################

# Attempt to set APP_HOME before any chdir
APP_HOME="`pwd -P`"

# Attempt to move the current working directory to the APP_HOME directory
cd "$APP_HOME" || exit 1

# Check if JAVA_HOME is set
if [ -n "$JAVA_HOME" ] ; then
    JAVA_EXE="$JAVA_HOME/bin/java"
    if [ ! -x "$JAVA_EXE" ] ; then
        echo "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME" >&2
        echo "Please set the JAVA_HOME variable in your environment to match the" >&2
        echo "location of your Java installation." >&2
        exit 1
    fi
else
    JAVA_EXE=java
fi

# Find Gradle Wrapper JAR
WRAPPER_JAR="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"
if [ ! -f "$WRAPPER_JAR" ]; then
    echo "ERROR: Could not find Gradle Wrapper JAR: $WRAPPER_JAR" >&2
    echo "Please run: gradle wrapper" >&2
    exit 1
fi

# Execute Gradle
exec "$JAVA_EXE" \
    -jar "$WRAPPER_JAR" \
    "$@"
